_wandb:
    value:
        cli_version: 0.23.1
        e:
            agpqjhok7h0ng7isi4ztegektajcy1ay:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "536870912000"
                        used: "320870842368"
                email: tungpham010203@gmail.com
                executable: /venv/bell/bin/python
                git:
                    commit: 9ce1d007924d22078d0fb2068ed2b5da9ac9fed5
                    remote: https://github.com/phongtintruong/annabelle.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-1cabd510-3a4e-aa55-26a7-5831e814c6e4
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-ce404171-12bd-1c99-7af4-4d68a9019469
                host: e80492e5ba41
                memory:
                    total: "404849147904"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /workspace/bell_llm/train.py
                python: CPython 3.10.19
                root: /workspace/bell_llm
                startedAt: "2025-12-18T16:06:09.621137Z"
                writerId: agpqjhok7h0ng7isi4ztegektajcy1ay
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 13
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.1
            "12": 0.23.1
            "13": linux-x86_64
